package gateway

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// fakeBackend is an in-process stand-in for the model server. It records the
// exact request body it received and returns a configurable status and body.
type fakeBackend struct {
	server     *httptest.Server
	gotBody    []byte
	gotPath    string
	gotCT      string
	respStatus int
	respBody   string
	respCT     string
}

func newFakeBackend(t *testing.T, status int, body, contentType string) *fakeBackend {
	t.Helper()
	fb := &fakeBackend{respStatus: status, respBody: body, respCT: contentType}
	fb.server = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fb.gotBody, _ = io.ReadAll(r.Body)
		fb.gotPath = r.URL.Path
		fb.gotCT = r.Header.Get("Content-Type")
		if fb.respCT != "" {
			w.Header().Set("Content-Type", fb.respCT)
		}
		w.WriteHeader(fb.respStatus)
		_, _ = io.WriteString(w, fb.respBody)
	}))
	t.Cleanup(fb.server.Close)
	return fb
}

// baseURL returns the backend base including the "/v1" segment, matching how the
// gateway is configured in production.
func (fb *fakeBackend) baseURL() string { return fb.server.URL + "/v1" }

const sampleCompletion = `{"id":"chatcmpl-1","object":"chat.completion","created":1,` +
	`"model":"llama3.2:1b","choices":[{"index":0,"message":{"role":"assistant",` +
	`"content":"Hello!"},"finish_reason":"stop"}],` +
	`"usage":{"prompt_tokens":5,"completion_tokens":2,"total_tokens":7}}`

func postChat(h http.Handler, body string) *httptest.ResponseRecorder {
	req := httptest.NewRequest(http.MethodPost, "/v1/chat/completions", strings.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	rec := httptest.NewRecorder()
	h.ServeHTTP(rec, req)
	return rec
}

// TestChatHappyPath: a normal request is forwarded and the backend's response is
// returned unchanged (status, body, content-type), and it reached the right path.
func TestChatHappyPath(t *testing.T) {
	fb := newFakeBackend(t, http.StatusOK, sampleCompletion, "application/json")
	h := newTestServer(fb.baseURL()).Handler()

	rec := postChat(h, `{"model":"llama3.2:1b","messages":[{"role":"user","content":"hi"}]}`)

	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200 (body: %s)", rec.Code, rec.Body.String())
	}
	if rec.Body.String() != sampleCompletion {
		t.Errorf("response body altered.\n got: %s\nwant: %s", rec.Body.String(), sampleCompletion)
	}
	if ct := rec.Header().Get("Content-Type"); ct != "application/json" {
		t.Errorf("Content-Type = %q, want application/json", ct)
	}
	if fb.gotPath != "/v1/chat/completions" {
		t.Errorf("backend path = %q, want /v1/chat/completions", fb.gotPath)
	}
	if fb.gotCT != "application/json" {
		t.Errorf("backend Content-Type = %q, want application/json", fb.gotCT)
	}
}

// TestChatBackendError: when the backend returns a non-2xx with an OpenAI-shaped
// error body, the gateway relays both the status and the body verbatim.
func TestChatBackendError(t *testing.T) {
	backendErr := `{"error":{"message":"model not found","type":"invalid_request_error"}}`
	fb := newFakeBackend(t, http.StatusNotFound, backendErr, "application/json")
	h := newTestServer(fb.baseURL()).Handler()

	rec := postChat(h, `{"model":"missing","messages":[]}`)

	if rec.Code != http.StatusNotFound {
		t.Fatalf("status = %d, want 404", rec.Code)
	}
	if rec.Body.String() != backendErr {
		t.Errorf("error body altered.\n got: %s\nwant: %s", rec.Body.String(), backendErr)
	}
}

// TestChatBackendUnreachable: a transport failure (nothing listening) becomes a
// 502 with an OpenAI-shaped error envelope generated by the gateway.
func TestChatBackendUnreachable(t *testing.T) {
	// A port on localhost with (almost certainly) nothing listening.
	h := newTestServer("http://127.0.0.1:1/v1").Handler()

	rec := postChat(h, `{"model":"x","messages":[]}`)

	if rec.Code != http.StatusBadGateway {
		t.Fatalf("status = %d, want 502", rec.Code)
	}
	var env errorEnvelope
	if err := json.Unmarshal(rec.Body.Bytes(), &env); err != nil {
		t.Fatalf("error body is not valid JSON envelope: %v (%s)", err, rec.Body.String())
	}
	if env.Error.Type != "upstream_error" || env.Error.Message == "" {
		t.Errorf("unexpected error envelope: %+v", env.Error)
	}
}

// TestChatUnknownFieldPreserved is the brief's key requirement: a client field
// we do not model must reach the backend untouched. We send both a real-but-
// unmodeled OpenAI param ("seed") and an entirely custom key, then check the
// bytes the backend received.
func TestChatUnknownFieldPreserved(t *testing.T) {
	fb := newFakeBackend(t, http.StatusOK, sampleCompletion, "application/json")
	h := newTestServer(fb.baseURL()).Handler()

	reqBody := `{"model":"llama3.2:1b","messages":[{"role":"user","content":"hi"}],` +
		`"seed":42,"x_semblance_custom":{"nested":true},"logit_bias":{"50256":-100}}`
	rec := postChat(h, reqBody)
	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d, want 200", rec.Code)
	}

	// The backend must have received exactly the original bytes.
	if string(fb.gotBody) != reqBody {
		t.Fatalf("forwarded body differs from original.\n got: %s\nwant: %s", fb.gotBody, reqBody)
	}
	// And, defensively, the unknown fields are individually present.
	var got map[string]json.RawMessage
	if err := json.Unmarshal(fb.gotBody, &got); err != nil {
		t.Fatalf("backend body not JSON: %v", err)
	}
	for _, key := range []string{"seed", "x_semblance_custom", "logit_bias"} {
		if _, ok := got[key]; !ok {
			t.Errorf("unknown field %q was dropped in transit", key)
		}
	}
}

// TestChatInvalidJSON: a body that is not JSON is rejected with 400 before any
// backend call.
func TestChatInvalidJSON(t *testing.T) {
	h := newTestServer("http://127.0.0.1:1/v1").Handler() // must not be reached
	rec := postChat(h, `not json at all`)

	if rec.Code != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400", rec.Code)
	}
	var env errorEnvelope
	if err := json.Unmarshal(rec.Body.Bytes(), &env); err != nil {
		t.Fatalf("error body not a valid envelope: %v", err)
	}
	if env.Error.Type != "invalid_request_error" {
		t.Errorf("error type = %q, want invalid_request_error", env.Error.Type)
	}
}
